### ISSUE TITLE
varlens-variants: correctly handle duplicate variants from multiple files

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varlens#12]
When gathering read evidence in `varlens-variants`, if you specify a variant more than once (via multiple VCF files), you currently get a failure unless you say `--distinct-variants`, which then causes a huge CSV with tons of metadata output to be written.

**Comment by arahuja** [comment]
Ran into this as well, when trying the sample command in https://github.com/hammerlab/biokepi/issues/119 on some sample VCFs. The idea there - merging VCFs from different aligners or callers - depends on this right? Or is there a workaround?
