### ISSUE TITLE
cleanup varlens and make a pip release

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/varlens#13]
If we're using this for pgv that's a good impetus to
 * write docs
 * figure out a way to demote the Python-expression-on-the-commandline stuff to still be there when you need the flexibility but be less in the way in the code
 * add unit tests for all the `--include-X` arguements in `varlens-variants`
 * do a pip release

**Comment by hammer** [comment]
Done right? https://pypi.python.org/pypi/varlens/

**Comment by timodonnell** [comment]
Yep.
