### ISSUE TITLE
Deploy to PyPi with Travis?

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/varlens#23]
@timodonnell I assume you're manually deploying to PyPi at the moment?

**Comment by timodonnell** [comment]
Yeah! Do you have tips for getting travis to do this?

**Comment by tavinathanson** [comment]
We talked offline about what this entails:

* Install the Travis CLI, grab the `hammerlab` password and encrypt it. (Also see internal wiki: "Releasing a Project".)
* Take the encrypted password and drop it into a Travis section like this one: https://github.com/hammerlab/varcode/blob/master/.travis.yml#L51

First, trying to figure out why Travis doesn't appear to be running.

**Comment by tavinathanson** [comment]
Talked offline; looks like the Travis config has syntax errors, and that triggers no building!

**Comment by tavinathanson** [comment]
According to https://lint.travis-ci.org, the problem appears to be in this line:

`- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-gh-pages.sh=`

**Comment by tavinathanson** [comment]
Closed by #24
